# Generated by Django 3.0.5 on 2020-05-09 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 20, 21, 49, 480812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='duty',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 20, 21, 49, 480840, tzinfo=utc)),
        ),
    ]
